from __future__ import annotations

import asyncio
import logging
from pathlib import Path

from devdex.models import DevDexPipelineState, GeneratedArtifact
from devdex.prompts import landing_page

logger = logging.getLogger(__name__)

DISCLAIMER = (
    "\n<!-- Generated by DevDex. "
    "Output quality depends on the model you have chosen. "
    "Review and customize before publishing. -->\n"
)

_TEMPLATE_DIR = Path(__file__).resolve().parent.parent.parent / "templates"


def _strip_code_fences(content: str) -> str:
    if content.startswith("```html"):
        content = content[7:]
    if content.startswith("```"):
        content = content[3:]
    if content.endswith("```"):
        content = content[:-3]
    return content.strip()


def _load_template() -> str:
    template_path = _TEMPLATE_DIR / "landing_page_base.html"
    if template_path.exists():
        return template_path.read_text()
    return ""


async def _generate_supporting_page(
    page_type: str,
    state: DevDexPipelineState,
    client,
    model: str,
    landing_html: str,
    page_content: str = "",
) -> tuple[str, str]:
    pu = state.understanding
    filename = f"{page_type}.html"

    system_prompt = landing_page.SUPPORTING_PAGE_SYSTEM_PROMPT
    user_prompt = landing_page.build_supporting_page_prompt(
        page_type, pu, landing_html, page_content=page_content,
    )

    try:
        response = await client.chat.completions.create(
            model=model,
            messages=[
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": user_prompt},
            ],
            max_tokens=6144,
            temperature=0.5,
        )
        content = response.choices[0].message.content or ""
        content = _strip_code_fences(content) + DISCLAIMER
        return filename, content
    except Exception as e:
        logger.warning("Failed to generate %s: %s", page_type, e)
        return filename, ""


async def generate_landing_page_html(
    state: DevDexPipelineState,
    client,
    model: str,
    improvement_context: str = "",
) -> GeneratedArtifact:
    pu = state.understanding
    artifact = GeneratedArtifact(
        artifact_type="landing_page",
        file_path="landing-page/index.html",
        format="html",
        model_used=model,
    )

    template_html = _load_template()

    system_prompt = landing_page.SYSTEM_PROMPT
    if improvement_context:
        system_prompt += f"\n\nIMPROVEMENT NOTES FROM PAST USER FEEDBACK:\n{improvement_context}"

    user_prompt = landing_page.build_prompt(pu, template_html=template_html)
    artifact.system_prompt = system_prompt
    artifact.user_prompt = user_prompt

    try:
        response = await client.chat.completions.create(
            model=model,
            messages=[
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": user_prompt},
            ],
            max_tokens=8192,
            temperature=0.6,
        )
        content = response.choices[0].message.content or ""
        content = _strip_code_fences(content)
        landing_html = content
        artifact.content = content + DISCLAIMER
    except Exception as e:
        artifact.error = str(e)
        return artifact

    existing_content: dict[str, str] = {}
    if hasattr(state, "result") and state.result.artifacts:
        for a in state.result.artifacts:
            if a.artifact_type == "privacy_policy" and a.success:
                existing_content["privacy-policy"] = a.content
            elif a.artifact_type == "terms_of_service" and a.success:
                existing_content["terms-of-service"] = a.content

    supporting_tasks = [
        _generate_supporting_page(
            page_type, state, client, model, landing_html,
            page_content=existing_content.get(page_type, ""),
        )
        for page_type in ["privacy-policy", "terms-of-service", "support"]
    ]

    results = await asyncio.gather(*supporting_tasks, return_exceptions=True)

    for result in results:
        if isinstance(result, Exception):
            logger.warning("Supporting page generation failed: %s", result)
            continue
        filename, html_content = result
        if html_content:
            artifact.extra_files[f"landing-page/{filename}"] = html_content

    return artifact
